# Generated by Django 4.2.2 on 2023-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='баннер')),
                ('banner_file', models.ImageField(default='main/unknown.png', upload_to='main/', verbose_name='файл баннера')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
                'ordering': ('name',),
            },
        ),
    ]
