# Generated by Django 4.2.2 on 2023-08-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_file',
            field=models.ImageField(default='apps/main/static/banners/unknown.jpeg', upload_to='apps/main/static/banners', verbose_name='файл баннера'),
        ),
    ]
